name: photo_tools
channels:
  - defaults
dependencies:
  - pandas
  - pip
  - python
  - Pillow
  - conda-forge::pygraphviz
  - pip:
      - PyExifTool
      - sqlalchemy
      - pytest
      - ruamel-yaml
      - pydantic

